# Generated by Django 4.0.3 on 2022-03-30 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('creation_date', models.DateField(default=datetime.datetime(2022, 3, 30, 20, 58, 56, 368787, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('creation_date', models.DateField(default=datetime.datetime(2022, 3, 30, 20, 58, 56, 367301, tzinfo=utc))),
                ('upvotes', models.IntegerField(default=0)),
                ('author_name', models.CharField(max_length=30)),
                ('comments', models.ManyToManyField(to='postcrudapi.comment')),
            ],
        ),
    ]
